server.port: 8080

solon:
  app:
    name: 'admin'
    group: 'cn.easydat'
  serialization:
    json:
      dateAsFormat: 'yyyy-MM-dd HH:mm:ss' #配置日期格式（默认输出为时间戳）
      dateAsTimeZone: 'GMT+8' #配置时区
      dateAsTicks: false #将date转为毫秒数（和 dateAsFormat 二选一）
      longAsString: true #将long型转为字符串输出 （默认为false）
      boolAsInt: false   #将bool型转为字符串输出 （默认为false）
      nullStringAsEmpty: false
      nullBoolAsFalse: false
      nullNumberAsZero: false
      nullArrayAsEmpty: false
      nullAsWriteable: false #输出所有null值
      enumAsName: false #枚举使用名字（v2.2.1 后支持）
      
easydat:
  xss:
    # 过滤开关
    enabled: true
    # 排除路径
    excludes:
  # 安全配置
  security:
    # IP黑名单
    ips:
    # 放行白名单
    whites:
      - /captchaImage
      - /login
      - /logout
      - /solon-admin/**
      - /healthz
      - /doc.html
      - /swagger-resources
      - /swagger/*
  captcha:
    # 验证码开关
    enabled: true
    # 干扰类型: line 线段干扰、circle 圆圈干扰、shear 扭曲干扰
    invadeType: line
    # 验证码类型: math 四则运算、char 字符
    type: math
    
  # 代码生成
  gen:
    # 作者
    author: easydat
    # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
    packageName: cn.easydat.admin
    # 自动去除表前缀，默认是false
    autoRemovePre: true
    # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
    tablePrefix: sys_
sa-token:
  # token名称（同时也是 cookie名称）
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  # token有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期，单位：秒），默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  
# Redis配置
redis:
  cache_source:
    config: |
      singleServerConfig:
        address: redis://47.97.105.19:10086
        password: easydat#2024
        database: 2
        
        
# 动态数据源
ds:
  data_source:
    type: com.zaxxer.hikari.HikariDataSource
    # 严格模式（指定的源不存时，严格模式会抛异常；非严格模式用默认源）
    strict: true
    # default 或 master ，会做为动态源的默认源
    master:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://47.97.105.19:3306/bm?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
      username: bm
      password: tmx!4^DR%A#hZYkF
      
      
# 配置数据源对应的 mybatis 信息
mybatis:
  # 要与 DataSource bean 的名字对上
  data_source:
    # 实体扫描
    typeAliases:
      - cn.easydat.*.domain.*
    # mapper扫描
    mappers:
      # 如果没有对应 xml 文件的 mapper，必须配置一下 mapper 的扫描路径
      # - com.qingzhou.system.mapper.*
      # 如果有 xml 文件，只需要配置 xml 文件的扫描路径，xml 对应的 mapper 会自动关联进去
      - classpath:mapper/**/*.xml
    # Mybatis 的扩展配置（要与 FlexConfiguration 类的属性一一对应）
    configuration:
      cacheEnabled: false
      # 如果为 true，则要求所有 mapper 有 @Mapper 主解
      mapperVerifyEnabled: false
      mapUnderscoreToCamelCase: true
    # Mybatis-Flex 的全局配置（要与 FlexGlobalConfig 类的属性一一对应）
    globalConfig:
      printBanner: true
      # 逻辑删除字段
      logicDeleteColumn: del_flag
      # 主键配置
      keyConfig:
        # Auto自增
        keyType: Auto
        # value:
